### ISSUE TITLE
User Story - 01

### ISSUE THREAD

**Issue by Stephan-mit-Ph** [Stephan-mit-Ph/Capstone-Project#1]
## Value proposition

As an user
I want a list of all categories
to specify a product.

## Description

![Image](https://user-images.githubusercontent.com/119015779/230185187-e126ddd8-9933-4736-914f-e4865dcc8c00.png)

## Acceptance criteria

- [x] Header is displayed
- [x] Shopname/Logo is linked to the Homepage
- [x] Categories preview and link is displayed
- [x] Categories Page list all available Categories

## Tasks

- [x] Create a Homepage
- [x] Create a Header
- [x] Shop title is linked to the Homepage
- [x] Categories Page should be rendered dynamically
- [x] Go Back Button/Link is directed to the Homepage
