### ISSUE TITLE
User Story - 08

### ISSUE THREAD

**Issue by Stephan-mit-Ph** [Stephan-mit-Ph/Capstone-Project#10]
## Value proposition

As a User,
I would like to remove items
from the shopping cart.

## Description

![Image](https://user-images.githubusercontent.com/119015779/231294602-1b426cc3-de49-4edf-bac8-ee96835f04c6.png)

## Acceptance criteria

- [x] Header is fixed on top
- [x] Shopname/Logo is linked to the Homepage
- [x] The Product Preview is linked to the product detail page

## Tasks

- [x] Create a button to remove list items from the cart
- [x] Shop title is linked to the Homepage
- [x] Go Back Button/Link is directed to the product details page

**Comment by Satttoshi** [comment]
LGTM :rocket:
