### ISSUE TITLE
User Story - 07

### ISSUE THREAD

**Issue by Stephan-mit-Ph** [Stephan-mit-Ph/Capstone-Project#15]
## Value proposition

As a user, 
I would like to see more images on preview
on the product detail page

## Description

![Image](https://user-images.githubusercontent.com/119015779/232748786-1dab92a8-d592-4795-a1d2-0aa596f816ea.png)

## Acceptance criteria

- [x] The product detail page shows one product in lager preview
- [x] Three images should display as thumbnails
- [x] When the user click on a thumbnail, the image should be displayed in the larger preview

## Tasks

- [x] extend the product image with a thumbnail container
- [x] create an image array with a Thumbnail onClick function

**Comment by Stephan-mit-Ph** [comment]
.

**Comment by rabe200** [comment]
lgtm. clear instructions!
