### ISSUE TITLE
User Story - 05

### ISSUE THREAD

**Issue by Stephan-mit-Ph** [Stephan-mit-Ph/Capstone-Project#16]
## Value proposition

As a user, 
I want to add a product to my shopping cart
by click on a button

## Description

![Image](https://user-images.githubusercontent.com/119015779/232758484-0adf1f4c-e396-4763-833f-e2af2f23475a.png)

## Acceptance criteria

- [x] Add to cart button is displayed
- [x] Selected items can be added, by click on the button
- [x] data is stored in local storage
- [x] visible for the user in another user story

## Tasks

- [x] create a button
- [x] implement local storage
- [x] write a onClick function which add the values of the selected product

**Comment by Stephan-mit-Ph** [comment]
.

**Comment by rabe200** [comment]
selected item = item displayed ?

in tasks you mention localStorage - so - maybe implement a check criteria to ACriteria?

like: if refreshing the page added items stay in cart

you haven't mentioned in the acceptance critera where the items get added to (though i see it in the value proposition)

just my 2 cents :)
