### ISSUE TITLE
User Story - 09

### ISSUE THREAD

**Issue by Stephan-mit-Ph** [Stephan-mit-Ph/Capstone-Project#25]
## Value proposition

As an user
I want to get visual Feedback
if I added a product to my cart

## Description

![Image](https://user-images.githubusercontent.com/119015779/235076882-eb5f0afd-7a51-43f5-9b0f-0925188489f2.png)

## Acceptance criteria

- [x] The User get a visual Feedback by click on the add to cart button

## Tasks

- [x] Create a React Toast Container
- [x] Create a toast.success message
- [x] add message to the add to cart function

**Comment by AnjaSiewert** [comment]
LGTM, let's gooooo! 🚀
