### ISSUE TITLE
User Story - 10

### ISSUE THREAD

**Issue by Stephan-mit-Ph** [Stephan-mit-Ph/Capstone-Project#28]
## Value proposition

As an user
I want to  see my shopping cart, by click on a button,
without leaving the page.

## Description

![Image](https://user-images.githubusercontent.com/119015779/235303753-6b2c41c5-57a7-4896-8d13-653ad4e4279c.png)

![Image](https://user-images.githubusercontent.com/119015779/235303759-a297623c-8233-4799-a85e-ffa39ecb3489.png)

## Acceptance criteria

- [ ] The user can toggle a sidebar from the cart icon
- [ ] The sidebar ha a close button
- [ ] all items are displayed in the cart sidebar

## Tasks

- [ ] Recreate the Layout Component
- [ ] Add toggle function
- [ ] import ShoppingCart
- [ ] Delete Cart Page
