### ISSUE TITLE
User Story - 02

### ISSUE THREAD

**Issue by Stephan-mit-Ph** [Stephan-mit-Ph/Capstone-Project#3]
## Value proposition

As an user
I want a overview about all available
products in a selected category

## Description

![Image](https://user-images.githubusercontent.com/119015779/230401393-f5b197e7-2111-4427-a3d3-b61bc1c81cc3.png)

## Acceptance criteria

- [x] Header is fixed on top
- [x] Shopname/Logo is linked to the Homepage
- [x] Category list all all product in preview
- [x] Product name, price and are displayed

## Tasks

- [x] Create a dynamic Category page
- [x] Render a list of all containing products
- [x] Shop title is linked to the Homepage
- [x] Categories Page should be rendered dynamically
- [x] Go Back Button/Link is directed to the Categories Page
