### ISSUE TITLE
User Story - 03

### ISSUE THREAD

**Issue by Stephan-mit-Ph** [Stephan-mit-Ph/Capstone-Project#3]
## Value proposition

As an user
I want to get all product details
from a list item.

## Description

![Image](https://user-images.githubusercontent.com/119015779/229482791-3b4939a2-8676-4c75-883c-8056644a2b5d.png)

## Acceptance criteria

- [ ] The `ProductDetailPage` includes all product details

## Tasks

- [ ] Create `ProductCard` component
- [ ] All acceptance criteria marked with 🛍️ are covered by component testing

**Comment by FrankSiyli** [comment]
You could delete the unused .[ ] in Acceptance criteria. Rest LGTM
