### ISSUE TITLE
User Story - 03

### ISSUE THREAD

**Issue by Stephan-mit-Ph** [Stephan-mit-Ph/Capstone-Project#4]
## Value proposition

As an user
I want to see all product details
by choosing a product

## Description

![Image](https://user-images.githubusercontent.com/119015779/230399011-2ce7bd09-4d31-4fc2-acb5-fe21912bbdac.png)

## Acceptance criteria

- [x] Header is fixed on top
- [x] Shopname/Logo is linked to the Homepage
- [x] The Product Preview is linked to the product detail page
- [x] Product detail page list all details about the product
- [x] Back Link is directed to category page

## Tasks

- [x] Create a dynamic product detail page
- [x] Create a Link for the detail page in the product preview
- [x] Shop title is linked to the Homepage
- [x] Go Back Button/Link is directed to the Category Page
