### ISSUE TITLE
User Story - 04

### ISSUE THREAD

**Issue by Stephan-mit-Ph** [Stephan-mit-Ph/Capstone-Project#7]
## Value proposition

As a user I want to change the amount of items
before adding them to my shopping cart.

## Description

![Image](https://user-images.githubusercontent.com/119015779/231282001-05f411b8-2492-44e0-9b95-7b686c6a5613.png)

## Acceptance criteria

- [x] Header is fixed on top
- [x] Shopname/Logo is linked to the Homepage
- [x] The product detail page contains a counter to change the amount of products
- [x] The price should be updated on click

## Tasks

- [x] Create a Counter
- [x] The price should change dynamically by de-/increase the number of items

**Comment by augustinanders** [comment]
Nice short US!🚀
In my eyes the first and second `acceptance-criteria` do not really make sense for this `userstory`, since the `value-proposition` us only about the `counter`. I would put this to a Layout US.
