### ISSUE TITLE
User Story - 06

### ISSUE THREAD

**Issue by Stephan-mit-Ph** [Stephan-mit-Ph/Capstone-Project#8]
## Value proposition

As a user, 
I would like to check all added products 
in my shopping cart.

## Description

![Image](https://user-images.githubusercontent.com/119015779/231289149-ba924be6-922d-4352-bc39-f2c9d887273b.png)

## Acceptance criteria

- [x] Header is fixed on top
- [x] Shopname/Logo is linked to the Homepage
- [x] The shopping cart list a preview of all added products
- [x] The price should be displayed in total

## Tasks

- [x] Create Cart Logic
- [x] Set  State
- [x] Write a function for the total cost
- [x] Go Back Button/Link is directed to the product details page

**Comment by ella-blaupause** [comment]
Your wireframes are awesome 🚀
